version: '2.1' # because we use depends_on with condition
services:
  server:
    environment:
      # CLI_ARGS: "--foo bar" # put your additional command line args here

      # PUID/PGID: user/group id of .minetest/ directory. See also https://github.com/linuxserver/docker-minetest/blob/master/README.md#user--group-identifiers
      PUID: 1000
      PGID: 1000

      PG_HOST: db # postgres host (here: name of the service below)

    volumes:
      - ./.minetest/:/config/.minetest/

    ports:
      - "30000:30000/udp"

    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=mt
      - POSTGRES_PASSWORD=mt
      - POSTGRES_DB=mt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mt"]
      interval: 5s
      timeout: 5s
      retries: 5
